dist: xenial
sudo: require
language: cpp
compiler: gcc

install:
  - sudo apt-get install boost libboost-all-dev uuid-dev

env:
  - CPLUS_INCLUDE_PATH="/usr/local/include/:/usr/lib/:/usr/include/"

script:
  - sh scripts/build.sh

after_success:
  - bash <(curl -s https://codecov.io/bash)
